### ISSUE TITLE
Refresh of diagrams is too slow.

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/phase#18]

**Comment by Lovee93** [comment]
Hi there, 
I am unable to save the schema and use it in Saiku for further analysis. Or if you could tell me where does it get saved? Because as I refresh the phase window, it disappears. Kindly help.

**Comment by rpbouman** [comment]
@Lovee93 hey, this sounds like a very different issue you're experiencing.

Could you please open a separate issue? Be sure to be very specific and add as much information as possible, because your current question does not have enough information. 

Do you for example see any javascript runtime errors? What steps do I take to reproduce the problem?
